<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" exclude-result-prefixes="sitemap image video news mobile">
	<xsl:output method="html" indent="true" version="5.0" encoding="UTF-8" doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN" doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"/>
	<xsl:variable name="file" select="document('')"/>
	<xsl:variable name="site-url" select="substring-before(sitemap:sitemapindex/sitemap:sitemap[1]/sitemap:loc, 'sitemap_index.xml')"/>
	<xsl:template match="/">
		<html>
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style>
					body {
						font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
						font-size: 14px;
						color: #333;
						margin: 0;
					}
					#description {
						background-color: #f7f9fa;
						border-bottom: 1px solid #e1eaf0;
						color: #31536b;
						margin: 0;
						padding: 18px 20px;
					}
					#description h1 {
						color: #31536b;
						font-size: 1.5em;
						margin: 0 0 6px 0;
						font-weight: 600;
					}
					a {
						color: #0073aa;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					ul {
						margin: 0;
						list-style: none;
						padding: 10px 0;
					}
					#sitemap {
						margin: 20px;
						-webkit-box-shadow: 0 1px 2px rgba(0,0,0,.07);
						box-shadow: 0 1px 2px rgba(0,0,0,.07);
						background: #fff;
						padding: 15px;
						border-radius: 4px;
						-webkit-box-sizing: border-box;
						-moz-box-sizing: border-box;
						box-sizing: border-box;
					}
					#sitemap li a {
						display: block;
						padding: 5px 10px;
						font-size: 16px;
						border-bottom: 1px solid #eee;
						-webkit-transition: background-color 0.2s ease-in-out;
						-moz-transition: background-color 0.2s ease-in-out;
						transition: background-color 0.2s ease-in-out;
					}
					#sitemap li a:hover {
						background-color: #fafafa;
						text-decoration: none;
					}
					.pagination {
						display: block;
						padding: 10px 0;
						text-align: center;
					}
					.pagination a {
						display: inline-block;
						padding: 5px 10px;
						margin: 0 5px;
						background-color: #fafafa;
						border: 1px solid #eee;
						border-radius: 4px;
						-webkit-transition: all 0.2s ease-in-out;
						-moz-transition: all 0.2s ease-in-out;
						transition: all 0.2s ease-in-out;
					}
					.pagination a:hover {
						background-color: #f0f0f0;
						text-decoration: none;
					}
					.pagination .current {
						background-color: #0073aa;
						color: #fff;
						border-color: #0073aa;
					}
					.pagination .current:hover {
						background-color: #0073aa;
						color: #fff;
						text-decoration: none;
					}
					#site-info {
						margin: 20px 0;
						text-align: center;
						color: #999;
					}
				</style>
			</head>
			<body>
				<div id="description">
					<h1>XML Sitemap</h1>
					<p>This is an XML Sitemap generated by Rank Math SEO Plugin. <a href="https://rankmath.com/" target="_blank">Learn more about XML Sitemaps</a></p>
				</div>
				<div id="sitemap">
					<ul>
						<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
							<li>
								<a href="{sitemap:loc}">
									<xsl:value-of select="sitemap:loc"/>
								</a>
							</li>
						</xsl:for-each>
						<xsl:for-each select="sitemap:urlset/sitemap:url">
							<li>
								<a href="{sitemap:loc}">
									<xsl:value-of select="sitemap:loc"/>
								</a>
							</li>
						</xsl:for-each>
					</ul>
				</div>
				<div id="site-info">
					<p>Generated by Rank Math SEO Plugin</p>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>